"""LLM backend abstraction.

The Implementer depends only on ``LLMClient``. The walking skeleton uses the
``DeterministicStub`` so a REAL pytest verifies a REAL fix with no network. Real
runs swap in ``ClaudeCLIClient`` (default) or ``AnthropicClient`` via config.
"""

from __future__ import annotations

import json
import re
from abc import ABC, abstractmethod
from pathlib import Path

from ..artifacts import Patch, Plan, Step
from ..live_context.models import ContextBundle

_DIFF_FENCE = re.compile(r"```(?:diff|patch)?\s*\n(.*?)```", re.DOTALL)
_JSON_FENCE = re.compile(r"```(?:json)?\s*\n(.*?)```", re.DOTALL)

_PLAN_SYSTEM = (
    "You are the planning agent of a verification-first harness. Decompose the task "
    "into an ordered list of verifiable steps. Output ONLY a JSON object in a ```json "
    "fenced block with keys `summary` (string) and `steps` (array). Each step has: "
    "`step_id`, `kind` (code|experiment|context), `action` "
    "(gather_context|edit_code|run_experiment|answer_query), `goal`, and `verifiers` "
    "(subset of: pytest, ruff, psnr, ssim, reproducibility, freshness, citation). "
    "Mirror the structure of the example plan. Do not explain."
)


def extract_json(text: str) -> str:
    m = _JSON_FENCE.search(text)
    if m:
        return m.group(1)
    s = text.strip()
    return s if s.startswith("{") else ""


_IMPL_SYSTEM = (
    "You are a careful software engineer. Given an issue, relevant code context, "
    "and the failing test output, produce a MINIMAL fix as a single unified diff "
    "in `git apply -p1` format (paths prefixed a/ and b/). Output ONLY the diff "
    "inside a ```diff fenced block. Do not explain."
)


def extract_unified_diff(text: str) -> str:
    m = _DIFF_FENCE.search(text)
    if m:
        return m.group(1)
    # fall back: assume the whole response is a diff if it looks like one
    if text.lstrip().startswith(("--- ", "diff --git")):
        return text
    return ""


class LLMClient(ABC):
    name: str = "base"

    @abstractmethod
    def complete(self, system: str, prompt: str) -> str: ...

    def plan(self, task, template: Plan) -> Plan | None:
        """Ask the LLM to (re)plan the task, or return None to use the caller's template.

        Real backends inherit this; the deterministic stub overrides it to return None
        so the default/eval path stays template-driven. Any parse/validation failure
        also yields None — the Supervisor then keeps its template plan.
        """
        prompt = (
            f"## Task\nkind: {task.kind}\ntitle: {task.title}\n"
            f"description: {task.description or task.title}\n\n"
            f"## Example plan for this task kind\n{template.model_dump_json(indent=2)}\n\n"
            "Return a JSON plan decomposing this task into verifiable steps."
        )
        try:
            data = json.loads(extract_json(self.complete(_PLAN_SYSTEM, prompt)) or "{}")
            steps = [Step.model_validate(s) for s in data.get("steps", [])]
            if not steps:
                return None
            return Plan(
                task_id=task.title,
                summary=data.get("summary", f"Plan: {task.title}"),
                steps=steps,
                overall_success=task.success or template.overall_success,
            )
        except Exception:
            return None

    def propose_patch(self, step, bundle: ContextBundle, workdir: str | Path) -> Patch:
        """Default: prompt the model with context and parse a unified diff."""
        workdir = Path(workdir)
        ctx_text = "\n\n".join(f"# {i.provenance.locator}\n{i.text}" for i in bundle.items[:8])
        files_text = self._read_repo_python(workdir)
        prompt = (
            f"## Issue\n{step.goal}\n\n"
            f"## Prior failures (if any)\n{chr(10).join(step.prior_failures) or 'none'}\n\n"
            f"## Retrieved context\n{ctx_text or 'none'}\n\n"
            f"## Repository files\n{files_text}\n\n"
            "Return the unified diff that fixes the issue."
        )
        response = self.complete(_IMPL_SYSTEM, prompt)
        diff = extract_unified_diff(response)
        touched = _touched_from_diff(diff)
        return Patch(
            step_id=step.step_id,
            unified_diff=diff,
            touched_files=touched,
            rationale=f"Generated by {self.name}.",
            based_on_context=bundle.locators(),
        )

    @staticmethod
    def _read_repo_python(workdir: Path, limit: int = 12) -> str:
        parts = []
        for p in sorted(workdir.rglob("*.py")):
            if ".cocoindex_code" in p.parts:
                continue
            rel = p.relative_to(workdir)
            parts.append(f"### {rel}\n{p.read_text()}")
            if len(parts) >= limit:
                break
        return "\n\n".join(parts)


def _touched_from_diff(diff: str) -> list[str]:
    files: list[str] = []
    for line in diff.splitlines():
        if line.startswith("+++ b/"):
            files.append(line[len("+++ b/") :].strip())
    return files
